"""zemtik init langchain — scaffold govern.yaml from LangChain tool introspection.

DEVELOPER-ONLY CLI: ``--tools-module`` accepts arbitrary Python import paths.
Never expose this command to untrusted input in production environments.

Usage::

    # Minimal govern.yaml (no tools introspected):
    python -m zemtik_govern.cli init langchain

    # Introspect tools from a module and pipe to file:
    python -m zemtik_govern.cli init langchain --tools-module my_agent.tools > govern.yaml

    # Write directly to a file instead of stdout:
    python -m zemtik_govern.cli init langchain --tools-module my_agent.tools --output govern.yaml

stdout/stderr discipline:
  - YAML output → stdout only (enables shell redirection)
  - Warnings / status messages → stderr
  - Import failure → NO YAML to stdout, error to stderr, exit(1)
  - Dynamic @tool schema → placeholder entry + warning to stderr (not a hard error)
"""
from __future__ import annotations

import argparse
import importlib
import sys
from typing import IO, Any

# ---------------------------------------------------------------------------
# YAML header — always emitted
# ---------------------------------------------------------------------------

_YAML_HEADER = """\
# generated by `zemtik init langchain`
# Uncomment rules to allow specific tools; everything is denied by default.
mode: strict
audit_sink: memory
rules:
"""

_YAML_EMPTY_RULES = "  []\n"

_YAML_RULES_COMMENT_PREFIX = "  # generated from tool introspection — uncomment to allow\n"


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------


def _is_langchain_tool(obj: Any) -> bool:
    """Return True if obj looks like a LangChain tool (duck-typed)."""
    return hasattr(obj, "name") and isinstance(getattr(obj, "name", None), str)


def _discover_tools(module: Any) -> list[Any]:
    """Return all LangChain-tool-like objects in *module*."""
    tools = []
    for attr_name in dir(module):
        if attr_name.startswith("_"):
            continue
        obj = getattr(module, attr_name, None)
        if obj is not None and _is_langchain_tool(obj):
            tools.append(obj)
    return tools


def _has_static_schema(tool: Any) -> bool:
    """Return True if the tool has a static (inspectable) args schema."""
    schema = getattr(tool, "args_schema", None)
    if schema is None:
        return False
    # pydantic v2 / v1 model: has model_fields or __fields__
    if hasattr(schema, "model_fields") or hasattr(schema, "__fields__"):
        return True
    return False


def _rule_name(tool_name: str) -> str:
    """Convert a tool name like send_email → allow-send-email."""
    return "allow-" + tool_name.replace("_", "-")


def _render_commented_rule(tool: Any) -> str:
    """Render a single tool as a commented-out YAML rule block."""
    name = tool.name
    rule_name = _rule_name(name)
    lines = [
        f"  # - name: {rule_name}",
        f"  #   condition: {{field: action, operator: eq, value: {name}}}",
        "  #   action: allow",
    ]
    return "\n".join(lines) + "\n"


def _render_dynamic_placeholder(tool: Any) -> str:
    """Render a placeholder comment for a tool with a dynamic schema."""
    name = tool.name
    rule_name = _rule_name(name)
    lines = [
        f"  # - name: {rule_name}  # WARNING: dynamic schema — inspect manually",
        f"  #   condition: {{field: action, operator: eq, value: {name}}}",
        "  #   action: allow",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Core generation function
# ---------------------------------------------------------------------------


def generate_govern_yaml(
    tools_module: str | None = None,
    output: str | None = None,
    stdout: IO[str] | None = None,
    stderr: IO[str] | None = None,
) -> int:
    """Generate govern.yaml content and write to *output* file or stdout.

    Parameters
    ----------
    tools_module:
        Dotted Python module path to import for tool introspection.
        When None, emit a minimal YAML header with empty rules.
    output:
        File path to write YAML to. When None, write to *stdout* stream.
    stdout:
        Stream to write YAML to when *output* is None. Defaults to sys.stdout.
    stderr:
        Stream to write warnings/errors to. Defaults to sys.stderr.

    Returns
    -------
    int
        Exit code: 0 on success, 1 on import failure.
    """
    _stdout = stdout if stdout is not None else sys.stdout
    _stderr = stderr if stderr is not None else sys.stderr

    # --- import phase (fail-closed) ----------------------------------------
    tools: list[Any] = []
    if tools_module is not None:
        try:
            mod = importlib.import_module(tools_module)
        except ImportError as exc:
            print(
                f"ERROR: cannot import '{tools_module}': {exc}",
                file=_stderr,
            )
            return 1
        tools = _discover_tools(mod)

    # --- render phase -------------------------------------------------------
    parts: list[str] = [_YAML_HEADER]

    if not tools:
        parts.append(_YAML_EMPTY_RULES)
    else:
        parts.append(_YAML_RULES_COMMENT_PREFIX)
        for tool in tools:
            if _has_static_schema(tool):
                parts.append(_render_commented_rule(tool))
            else:
                # Dynamic schema — emit placeholder + stderr warning
                print(
                    f"WARNING: tool '{tool.name}' has a dynamic schema; "
                    "emitting placeholder comment — review manually.",
                    file=_stderr,
                )
                parts.append(_render_dynamic_placeholder(tool))

    yaml_content = "".join(parts)

    # --- output phase -------------------------------------------------------
    if output is not None:
        with open(output, "w", encoding="utf-8") as fh:
            fh.write(yaml_content)
    else:
        print(yaml_content, end="", file=_stdout)

    return 0


# ---------------------------------------------------------------------------
# CLI argument parsing
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="zemtik init langchain",
        description=(
            "Scaffold a govern.yaml from LangChain tool introspection. "
            "DEVELOPER-ONLY: --tools-module accepts arbitrary imports."
        ),
    )
    parser.add_argument(
        "--tools-module",
        metavar="MODULE",
        default=None,
        help="Dotted path of the Python module containing LangChain tools to introspect.",
    )
    parser.add_argument(
        "--output",
        metavar="FILE",
        default=None,
        help="Write govern.yaml to FILE instead of stdout.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Entry point for `zemtik init langchain`."""
    parser = _build_parser()
    # Strip the leading 'init langchain' tokens if invoked from the top-level dispatcher.
    # argparse only needs the flags; positional dispatch is handled by __main__.py.
    if argv is None:
        # Drop 'init langchain' from sys.argv if present (top-level dispatch).
        raw = sys.argv[1:]
        # Filter out 'init' and 'langchain' positional tokens at the front.
        while raw and raw[0] in ("init", "langchain"):
            raw = raw[1:]
        argv = raw

    args = parser.parse_args(argv)
    return generate_govern_yaml(tools_module=args.tools_module, output=args.output)


if __name__ == "__main__":
    sys.exit(main())
